name: 'Test the action locally (CI)'


on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Execute action
        uses: ./
        with:
          environment-file: ./tests/test_env.yml
          enable-html: true
          enable-pdf: true

      - name: Upload html results as artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: compiled-notebooks-html
          path: "**/*.html"

      - name: Upload pdf results as artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: compiled-notebooks-pdf
          path: "**/*.pdf"
